<?php

/**
 * Tokens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tokens extends BaseTokens
{
	public static function getTokensByUserID($id){
		$mobiles = Doctrine_Core::getTable('Tokens')
     	->createQuery()
     	->addWhere("user_id =?",$id)  
     	->fetchArray();
    	 $array_token = array();
     	foreach ($mobiles as $comments){
        	array_push($array_token,$comments['device_id']);
     	}

      	return $array_token;
	}
	public static function arrayMergeTokens($tokens){
		$result= array();
		foreach ($tokens as $key => $value) {
			var_dump($value);
			$result =array_merge($result,$value);
		}
		return $result;
	}
}