<?php

/**
 * Tokens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tokens extends BaseTokens
{
	public static function getTokensByUserID($id){
		$mobiles = Doctrine_Core::getTable('Tokens')
     	->createQuery()
     	->addWhere("user_id =?",$id)  
     	->fetchArray();
    	 $array_token['android'] = array();
    	 $array_token['ios'] = array();
     	foreach ($mobiles as $comments){
     		//echo "<br>";
     		//var_dump($comments);
     		if ($comments['device_type'] == "1"){
     			array_push($array_token['android'],$comments['device_id']);

     		}else{
     			array_push($array_token['ios'],$comments['device_id']);
     		}
     	}
     	//echo "<br>";
     	//var_dump($array_token);
      	return $array_token;
	}
	public static function arrayMergeTokens($tokens){
		$result['android']= array();
		$result['ios']= array();
		foreach ($tokens as $key => $value) {
			//echo "<br>";
			//echo "key:".$key;
			//echo "<br>";

			var_dump($value);
				$result['android'] =array_merge($result['android'],$value['android']);
				$result['ios'] =array_merge($result['ios'],$value['ios']);
		}
		return $result;
	}
}